### ISSUE TITLE
Clarify RELIC dependency

### ISSUE THREAD

**Issue by raketeneis** [ace0/pyrelic#1]
I was trying to run a Pythia instance and couldn't get it to work with any official version of RELIC. After some time I saw that you had forked RELIC and that pyrelic depends on that fork.
Maybe you could clarify this somewhere.

Thanks!

**Comment by ace0** [comment]
Thanks for pointing this out! I added a note to the README with a link to my fork of RELIC. Do you think this helps?

Also, it's great that you're setting up Pythia! Let me know if you have questions, need, help, or just want to provide feedback. I'd like to see Pythia getting used in the world.

Cheers,
~ace

**Comment by raketeneis** [comment]
Thanks for adding the note! If I run into any problems, I will let you know.
